app/models/stories.py
"""This is an example model which will be used for creating stories on the web.
The model is defined in a similar way to python class/object, however is
inherited from a SQLAlchemy class so a DB entry with a table can be built
easily
"""

from datetime import datetime
from app import db


class Story(db.Model):
    # Table name which is going to store the stories defined here
    __tablename__ = 'stories'

    # These are the entries that are going to become columns in that table

    # Primary Key
    id = db.Column(db.Integer, primary_key=True)

    # Story
    title = db.Column(db.String(255))
    topic = db.Column(db.String(255))
    text = db.Column(db.Text())
    author = db.Column(db.String(255))
    created_at = db.Column(db.DateTime(), default=datetime.utcnow)

    def __init__(self, **kwargs):
        # Helps with class initiation, basically what every attribute you give
        # at initiaion will become a class attribute with this __init__ method
        super(Story, self).__init__(**kwargs)

    # The to json methods will be used for responding to API queries which are
    # going to be requesting story information.

    def to_full_json(self):
        json_story = {
            'id': self.id,
            'title': self.title,
            'topic': self.topic,
            'text': self.text,
            'author': self.author,
            'created_at': self.created_at,
        }
        return json_story

    def to_half_json(self):
        json_story = {
            'id': self.id,
            'title': self.title,
            'author': self.author,
            'created_at': self.created_at,
        }
        return json_story

    # This from json method is used for creating a story from a JSON.
    @staticmethod
    def from_json(json_post):
        title = json_post.get('title')
        topic = json_post.get('topic')
        text = json_post.get('text')
        author = json_post.get('author')

        story = Story(
            title=title,
            topic=topic,
            text=text,
            author=author
        )
        return story

app/main/forms.py
"""Create a form for creating stories"""

from wtforms.validators import DataRequired, Length
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    TextAreaField,
    SubmitField,
)

standard_validators = [DataRequired(), Length(0, 255)]


class StoryForm(FlaskForm):
    title = StringField('Title', validators=standard_validators)
    topic = StringField('Topic', validators=standard_validators)
    text = TextAreaField('Story', validators=[DataRequired()])
    author = StringField('Author', validators=standard_validators)
    submit = SubmitField('Submit')

app/__init__.py
"""This is where we create a function for initiating the application, which is
later on used at the very top level stories.py module to initiate the
application with a specific config file"""

# Flask Imports
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_migrate import Migrate
from flask import Flask

# Importing configs
from config import config_dict

# Setup

# We iniate the database and other packages that are going to play together
# with the app here

# For the database
db = SQLAlchemy()
# For database migrations
migrate = Migrate()
# For HTML bootstrapping
bootstrap = Bootstrap()


def create_app(config_key='local'):
    app = Flask(__name__)
    # Enabling config initiation
    app.config.from_object(config_dict[config_key])
    config_dict[config_key].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)

    # Registering the main and the api blueprints here
    from app.main import main as main_blueprint
    from app.api import api as api_blueprint

    app.register_blueprint(main_blueprint)
    app.register_blueprint(api_blueprint, url_prefix='/api/v1')

    return app

app/api/__init__.py
"""Initiates the API through Flask's blueprint"""

from flask import Blueprint
api = Blueprint('api', __name__)

# This import might seem unconventional, however is required to register your
# routes, which are created under the api folder. As you add more routes,
# you should import them here so the app can pick it up.

from app.api import stories

app/main/__init__.py
"""Initiates the main through Flask's blueprint"""

from flask import Blueprint

main = Blueprint('main', __name__)

# Similar to the API route import, in this case we need to import the views
# so it can be registered through the main blueprint.
from app.main import views

app/main/views.py
"""This is the views page, which is similar to what the routes do for the API.
The difference is rather than routes, this renders and displays HTML pages"""

from app.main.forms import StoryForm
from app.main import main
from flask import (
    render_template,
    redirect,
    url_for,
    abort,
    flash,
    request,
    current_app,
    make_response)
from app import db

from app.models.stories import Story


@main.route('/', methods=['GET', 'POST'])
def index():
    stories = Story.query.all()
    return render_template('index.html', stories=stories)

@main.route('/create-story', methods=['GET', 'POST'])
def create_story():
    form = StoryForm()
    if form.validate_on_submit():
        story = Story(
            title=form.title.data,
            topic=form.topic.data,
            text=form.text.data,
            author=form.text.data
        )
        db.session.add(story)
        db.session.commit()
        flash('Story created')
        return redirect(url_for('main.index'))
    return render_template('edit_story.html', form=form)

app/templates/base.html
{% extends "bootstrap/base.html" %}


{% block title %}Stories{% endblock %}

{% block head %}

{{ super() }}

<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">

{% endblock %}


{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Stories</a>
        </div>


        <div class="navbar-collapse collapse">


            <!-- Scheduler Nav Bar -->
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.create_story') }}">Create Story</a></li>
            </ul>


        </div>
    </div>
</div>
{% endblock %}



{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/edit_story.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Create Story{% endblock %}


{% block page_content %}
<div class="page-header">
    <h1>Create Story</h1>
  </div>


<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}

{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

<title>{% block title %}STORIES{% endblock %}</title>

{% block page_content %}

<div class="page-header">
  <h1>Stories</h1>
</div>


<div class="container">
    <ul class="stories">
        {% for story in stories %}
        <li class="stories">
            <div class="story-content">
                <div class="story-title">
                    <h3>{{story.title}}</h3>
                    <p>Topic: {{story.topic}}</p>
                    <p>Author: {{story.author}}</p>
                    <p>Created At: {{story.created_at}}</p>
                    <p>>>>{{story.text}}</p>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

{% block scripts %}
{{ super() }}

{% endblock %}